from pathlib import Path

from langchain_core.messages import HumanMessage, SystemMessage
from pydantic import BaseModel, Field

from app.agents.state import InvestigationState
from app.llm import get_chat_model
from app.models.confidence import ConfidenceScore
from app.models.evidence import Evidence
from app.models.fix import FixAttempt, FixOutcome, FixResult
from app.models.incident import IncidentSnapshot
from app.models.rca import RCA, FixStrategy
from app.policies import load_policies
from app.security.diff_policy import check_diff, touched_files
from app.services.repo_registry import get_service
from app.tools import github_api, repo_write
from app.tools.sandbox import SandboxResult, ensure_sandbox_image, run_in_sandbox

# Fixed path, never LLM-chosen — keeps the diff policy's per-file check
# meaningful and stops the LLM from scattering test files around the tree.
REPRO_TEST_PATH = "tests/test_agent_repro.py"

REPRO_SYSTEM = (
    "You write a single pytest test file that reproduces a bug, given an RCA "
    "and code evidence for a FastAPI service. Constraints: the test runs with "
    "NO network access and NO real database or external service — mock "
    "everything (unittest.mock, monkeypatch, or calling pure logic directly) "
    "needed to reach the buggy code path. Import only from the target repo "
    "and Python's standard library plus pytest/unittest.mock. The test MUST "
    "currently fail against the buggy code and must assert the CORRECT "
    "behavior once fixed. Write exactly one test function."
)

PATCH_SYSTEM = (
    "You write a minimal unified diff (git diff format: `diff --git a/<path> "
    "b/<path>` headers, `---`/`+++` lines, valid `@@` hunks) that fixes a bug, "
    "given an RCA, a failing repro test, and its failure output. Constraints: "
    "only touch files under app/ or tests/. Keep the change minimal and "
    "focused on the root cause. Never touch dependency, config, or CI files. "
    "Never skip or delete a test. Output ONLY the diff, nothing else."
)


class ReproTestOutput(BaseModel):
    test_code: str = Field(description="Full contents of the new pytest test file.")


class PatchOutput(BaseModel):
    unified_diff: str = Field(description="A complete unified diff in git format.")


def _passed_full_suite(result: SandboxResult) -> bool:
    # pytest exit 5 = "no tests collected" — vacuously fine on a repo that
    # currently ships zero tests; only real failures/errors count.
    return result.returncode in (0, 5)


def _truncated(*results: SandboxResult) -> str:
    text = "".join(r.stdout + r.stderr for r in results)
    return text[-4000:]


def _pr_body(
    incident: IncidentSnapshot, rca: RCA, confidence: ConfidenceScore, attempts: list[FixAttempt]
) -> str:
    evidence_lines = "\n".join(f"- {eid}" for eid in rca.evidence_ids) or "- (none cited)"
    attempt_lines = (
        "\n".join(
            f"- attempt {a.attempt}: tests_passed={a.tests_passed}, ruff_passed={a.ruff_passed}"
            + ("" if a.diff_policy_ok else f", rejected: {'; '.join(a.diff_policy_reasons)}")
            for a in attempts
        )
        or "- (none)"
    )
    return (
        f"## Incident {incident.key} — {incident.service}\n\n"
        f"**Root cause:** {rca.root_cause}\n\n"
        f"**Causal chain:** {' -> '.join(rca.causal_chain)}\n\n"
        f"**Evidence cited:**\n{evidence_lines}\n\n"
        f"**Confidence:** {confidence.score} ({confidence.band})\n\n"
        f"**Validation:**\n{attempt_lines}\n\n"
        f"**Unknowns:** {'; '.join(rca.unknowns) if rca.unknowns else 'none'}\n\n"
        "---\nGenerated by incident-triage-agent. Review required."
    )


def _publish(
    changes: dict[str, str | None],
    incident: IncidentSnapshot,
    rca: RCA,
    confidence: ConfidenceScore,
    strategy: FixStrategy,
    attempts: list[FixAttempt],
) -> FixResult:
    """Commits `changes` (path -> new content, or None to delete) straight
    through the GitHub REST API and opens the draft PR — no local `git
    commit`/`git push` anywhere (see repo_write.py's module docstring)."""
    branch = repo_write.branch_name(incident.key)
    message = f"[agent] fix for {incident.key}: {rca.root_cause[:72]}"

    github_api.ensure_remote_branch(branch, base="main")
    for path, content in changes.items():
        if content is None:
            github_api.delete_file_content(branch, path, message)
        else:
            github_api.put_file_content(branch, path, content, message)

    title = f"[agent] {incident.key}: {rca.root_cause[:72]}"
    pr_url = github_api.create_draft_pr(
        branch=branch, title=title, body=_pr_body(incident, rca, confidence, attempts)
    )
    return FixResult(
        outcome=FixOutcome.DRAFT_PR_OPENED, strategy=strategy.value, branch=branch, pr_url=pr_url,
        attempts=attempts,
    )  # fmt: skip


def _run_revert(
    repo_path: Path,
    scratch_dir: Path,
    image_tag: str,
    incident: IncidentSnapshot,
    rca: RCA,
    confidence: ConfidenceScore,
    attempts: list[FixAttempt],
) -> FixResult:
    if not rca.suspect_commit:
        return FixResult(
            outcome=FixOutcome.NEEDS_HUMAN,
            strategy=FixStrategy.REVERT_COMMIT.value,
            give_up_reason="RCA has fix_strategy=revert_commit but no suspect_commit",
        )

    changes = repo_write.apply_revert(repo_path, scratch_dir, rca.suspect_commit)
    suite_result = run_in_sandbox(scratch_dir, image_tag, "pytest_all")
    lint_result = run_in_sandbox(scratch_dir, image_tag, "ruff")
    tests_passed = _passed_full_suite(suite_result)
    ruff_passed = lint_result.passed

    attempts.append(
        FixAttempt(
            attempt=1,
            diff=f"git revert --no-edit {rca.suspect_commit}",
            diff_policy_ok=True,
            tests_passed=tests_passed,
            ruff_passed=ruff_passed,
            failure_output=""
            if (tests_passed and ruff_passed)
            else _truncated(suite_result, lint_result),
        )
    )
    if not (tests_passed and ruff_passed):
        return FixResult(
            outcome=FixOutcome.NEEDS_HUMAN,
            strategy=FixStrategy.REVERT_COMMIT.value,
            attempts=attempts,
            give_up_reason="reverted code failed the test suite or lint",
        )
    return _publish(changes, incident, rca, confidence, FixStrategy.REVERT_COMMIT, attempts)


def _run_code_change(
    repo_path: Path,
    scratch_dir: Path,
    image_tag: str,
    incident: IncidentSnapshot,
    rca: RCA,
    confidence: ConfidenceScore,
    evidence_bundle: list[Evidence],
    max_attempts: int,
    attempts: list[FixAttempt],
) -> FixResult:
    evidence_summary = "\n".join(f"[{e.id}] ({e.source}) {e.summary}" for e in evidence_bundle)

    repro_model = get_chat_model(tier="strong").with_structured_output(ReproTestOutput)
    repro = repro_model.invoke(
        [
            SystemMessage(REPRO_SYSTEM),
            HumanMessage(
                f"Root cause: {rca.root_cause}\nAffected component: {rca.affected_component}\n"
                f"Causal chain: {rca.causal_chain}\nEvidence:\n{evidence_summary}\n\n"
                "Write the repro test now."
            ),
        ]
    )

    def write_repro_test() -> None:
        repro_path = scratch_dir / REPRO_TEST_PATH
        repro_path.parent.mkdir(parents=True, exist_ok=True)
        repro_path.write_text(repro.test_code)

    write_repro_test()

    pre_fix = run_in_sandbox(scratch_dir, image_tag, "pytest_file", file=REPRO_TEST_PATH)
    if pre_fix.passed:
        return FixResult(
            outcome=FixOutcome.NEEDS_HUMAN,
            strategy=FixStrategy.CODE_CHANGE.value,
            give_up_reason="repro test did not fail on current (buggy) code — proves nothing",
        )

    failure_output = _truncated(pre_fix)
    patch_model = get_chat_model(tier="strong").with_structured_output(PatchOutput)

    for attempt_n in range(1, max_attempts + 1):
        patch = patch_model.invoke(
            [
                SystemMessage(PATCH_SYSTEM),
                HumanMessage(
                    f"Root cause: {rca.root_cause}\nAffected component: {rca.affected_component}\n"
                    f"Repro test (must pass after your patch):\n{repro.test_code}\n\n"
                    f"Failure output:\n{failure_output}\n\nWrite the patch now."
                ),
            ]
        )
        diff = patch.unified_diff
        policy_result = check_diff(diff)
        if not policy_result.allowed:
            attempts.append(
                FixAttempt(
                    attempt=attempt_n,
                    diff=diff,
                    diff_policy_ok=False,
                    diff_policy_reasons=policy_result.reasons,
                    tests_passed=False,
                    ruff_passed=False,
                )
            )
            failure_output = "diff rejected by policy: " + "; ".join(policy_result.reasons)
            continue

        try:
            repo_write.apply_patch(repo_path, scratch_dir, diff)
        except RuntimeError as exc:
            attempts.append(
                FixAttempt(
                    attempt=attempt_n, diff=diff, diff_policy_ok=True,
                    tests_passed=False, ruff_passed=False, failure_output=str(exc),
                )
            )  # fmt: skip
            failure_output = str(exc)
            repo_write.prepare_scratch_copy(repo_path, incident.key)  # reset to clean origin/main
            write_repro_test()
            continue

        repro_result = run_in_sandbox(scratch_dir, image_tag, "pytest_file", file=REPRO_TEST_PATH)
        suite_result = run_in_sandbox(scratch_dir, image_tag, "pytest_all")
        lint_result = run_in_sandbox(scratch_dir, image_tag, "ruff")
        tests_passed = repro_result.passed and _passed_full_suite(suite_result)
        ruff_passed = lint_result.passed

        attempts.append(
            FixAttempt(
                attempt=attempt_n,
                diff=diff,
                diff_policy_ok=True,
                repro_test_failed_before=True,
                tests_passed=tests_passed,
                ruff_passed=ruff_passed,
                failure_output=(
                    ""
                    if (tests_passed and ruff_passed)
                    else _truncated(repro_result, suite_result, lint_result)
                ),  # fmt: skip
            )
        )

        if tests_passed and ruff_passed:
            changes: dict[str, str | None] = {}
            for path in touched_files(diff):
                full = scratch_dir / path
                changes[path] = full.read_text() if full.exists() else None
            changes[REPRO_TEST_PATH] = repro.test_code
            return _publish(changes, incident, rca, confidence, FixStrategy.CODE_CHANGE, attempts)

        failure_output = attempts[-1].failure_output
        repo_write.prepare_scratch_copy(repo_path, incident.key)  # reset to clean origin/main
        write_repro_test()

    return FixResult(
        outcome=FixOutcome.NEEDS_HUMAN,
        strategy=FixStrategy.CODE_CHANGE.value,
        attempts=attempts,
        give_up_reason=f"exhausted {max_attempts} attempts",
    )


def run_fix(state: InvestigationState) -> dict:
    """The fix subgraph (doc section 9.2), run as one bounded node rather than
    N graph nodes — same pattern as code_investigation's agentic loop: the
    retry loop is inherently sequential and stateful, so a single Python
    function owns it rather than fighting LangGraph's edge system to express
    a retry with feedback.

    Validation runs against a plain filesystem snapshot (repo_write.py's
    scratch copy), and the actual commit — once validation passes — is made
    through the GitHub REST API rather than local git. See repo_write.py's
    module docstring for why: this machine's commit guardrail blocks any
    commit made inside a git worktree, so local git commit is a dead end for
    this subgraph regardless of isolation strategy."""
    incident = state["incident"]
    rca = state["rca"]
    confidence = state["confidence"]
    max_attempts = load_policies()["fix"]["max_attempts"]

    try:
        service_cfg = get_service(incident.service)
    except (KeyError, ValueError) as exc:
        return {
            "fix": FixResult(
                outcome=FixOutcome.NEEDS_HUMAN,
                strategy=rca.fix_strategy.value,
                give_up_reason=str(exc),
            )
        }

    repo_path = service_cfg.repo_path
    attempts: list[FixAttempt] = []
    try:
        scratch_dir = repo_write.prepare_scratch_copy(repo_path, incident.key)
        image_tag = ensure_sandbox_image(repo_path)

        if rca.fix_strategy == FixStrategy.REVERT_COMMIT:
            result = _run_revert(
                repo_path, scratch_dir, image_tag, incident, rca, confidence, attempts
            )
        else:
            result = _run_code_change(
                repo_path, scratch_dir, image_tag, incident, rca, confidence,
                state["evidence_bundle"], max_attempts, attempts,
            )  # fmt: skip
    except Exception as exc:
        result = FixResult(
            outcome=FixOutcome.NEEDS_HUMAN,
            strategy=rca.fix_strategy.value,
            attempts=attempts,
            give_up_reason=f"unexpected error: {exc}",
        )

    repo_write.discard_scratch_copy(incident.key)
    return {"fix": result}
